version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: smarttodo_prod
      POSTGRES_USER: smarttodo_user
      POSTGRES_PASSWORD: secure_production_password
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - PORT=8000
      - DATABASE_URL=postgres://smarttodo_user:smarttodo_pass@db:5432/smarttodo_prod
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api

volumes:
  postgres_data: