version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: smarttodo_prod
      POSTGRES_USER: smarttodo_user
      POSTGRES_PASSWORD: secure_production_password
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DB_NAME=smarttodo_db
      - DB_USER=smarttodo_user
      - DB_PASSWORD=smarttodo_pass
      - DB_HOST=localhost
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api

volumes:
  postgres_data: