### Create a habit
POST http://127.0.0.1:5000/api/habits
Content-Type: application/json

{
  "name": "Read Book",
  "frequency": "daily"
}

### Get all habits
GET http://127.0.0.1:5000/api/habits

### Get habit by ID
GET http://127.0.0.1:5000/api/habits/{{habitId}}

### Update a habit
PUT http://127.0.0.1:5000/api/habits/{{habitId}}
Content-Type: application/json

{
  "name": "Read a Book - Updated",
  "frequency": "weekly"
}

### Delete a habit
DELETE http://127.0.0.1:5000/api/habits/{{habitId}}
