# Generated by Django 5.2.5 on 2025-08-31 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.URLField()),
                ('platform', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('api_key', models.CharField(editable=False, max_length=100, unique=True)),
                ('webhook_secret', models.CharField(editable=False, max_length=100)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due')], default='trial', max_length=20)),
                ('subscription_plan', models.CharField(default='starter', max_length=50)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_message', models.TextField(default="Hi! I'm here to help you with any questions about our store.")),
                ('escalation_message', models.TextField(default='Let me connect you with a human representative.')),
                ('theme_color', models.CharField(default='#007bff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.store')),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'question'],
            },
        ),
        migrations.CreateModel(
            name='StoreIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_shop_name', models.CharField(blank=True, max_length=100)),
                ('shopify_access_token', models.CharField(blank=True, max_length=200)),
                ('woocommerce_consumer_key', models.CharField(blank=True, max_length=200)),
                ('woocommerce_consumer_secret', models.CharField(blank=True, max_length=200)),
                ('sync_products', models.BooleanField(default=True)),
                ('sync_orders', models.BooleanField(default=True)),
                ('sync_customers', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='core.store')),
            ],
        ),
    ]
